const stopWords = [
  "a", "about", "above", "after", "again", "against", "ain", "all", "am", "an", "and", "any", "are", "aren", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "can", "could", "couldn", "d", "did", "didn", "do", "does", "doesn", "doing", "don", "down", "during", "each", "few", "for", "from", "further", "had", "hadn", "has", "hasn", "have", "haven", "having", "he", "her", "here", "hers", "herself", "him", "himself", "his", "how", "i", "if", "in", "into", "is", "isn", "it", "its", "itself", "just", "ll", "m", "ma", "me", "mightn", "more", "most", "mustn", "my", "myself", "needn", "no", "nor", "not", "now", "o", "of", "off", "on", "once", "only", "or", "other", "our", "ours", "ourselves", "out", "over", "own", "re", "s", "same", "shan", "she", "should", "shouldn", "so", "some", "such", "t", "than", "that", "the", "their", "theirs", "them", "themselves", "then", "there", "these", "they", "this", "those", "through", "to", "too", "under", "until", "up", "ve", "very", "was", "wasn", "we", "were", "weren", "what", "when", "where", "which", "while", "who", "whom", "why", "will", "with", "won", "would", "wouldn", "y", "you", "your", "yours", "yourself", "yourselves", "ain’t", "aren’t", "can’t", "could’ve", "couldn’t", "didn’t", "doesn’t", "don’t", "hadn’t", "hasn’t", "haven’t", "he’d", "he’ll", "he’s", "how’d", "how’ll", "how’s", "i’d", "i’ll", "i’m", "i’ve", "isn’t", "it’d", "it’ll", "it’s", "let’s", "might’ve", "mightn’t", "must’ve", "mustn’t", "shan’t", "she’d", "she’ll", "she’s", "should’ve", "shouldn’t", "that’ll", "that’s", "there’s", "they’d", "they’ll", "they’re", "they’ve", "wasn’t", "we’d", "we’ll", "we’re", "we’ve", "weren’t", "what’d", "what’s", "when’d", "when’ll", "when’s", "where’d", "where’ll", "where’s", "who’d", "who’ll", "who’s", "why’d", "why’ll", "why’s", "won’t", "would’ve", "wouldn’t", "you’d", "you’ll", "you’re", "you’ve", "got", "went", "gone", "come", "comes", "came", "get", "gets", "getting", "doing", "done", "being", "want", "wants", "wanted", "like", "likes", "liked", "know", "knows", "knew", "known", "make", "makes", "made", "see", "saw", "seen", "use", "used", "using", "go", "goes", "going", "have", "had", "has", "do", "did", "does", "keep", "keeps", "kept", "let", "lets", "say", "says", "said", "think", "thinks", "thought", "try", "tries", "tried", "need", "needs", "needed", "look", "looks", "looked", "seem", "seems", "seemed", "give", "gives", "gave", "find", "finds", "found", "tell", "tells", "told", "ask", "asks", "asked", "work", "works", "worked", "feel", "feels", "felt", "call", "calls", "called"
];

export function removeStopWords(text: string): string {
  return text
    .split(/\s+/)
    .filter(word => !stopWords.includes(word.toLowerCase()))
    .join(' ');
}